import Employee from "@/components/Employee"
export const metadata = {
  title: {
    // absolute: "",
    default: "Employee",
    template: "%s",
  },
  description: "Generated by create next app",
};
const page = () => {
  return (
    <Employee />
  )
}

export default page