import MaintenanceInvoices from '@/components/MaintenanceInvoices'
export const metadata = {
  title: {
    // absolute: "",
    default: "MaintenanceInvoices",
    template: "%s",
  },
  description: "Generated by create next app",
};
const page = () => {
  return (
    <MaintenanceInvoices />
  )
}

export default page