import Suppliers from "@/components/Suppliers"
export const metadata = {
  title: {
    // absolute: "",
    default: "Suppliers",
    template: "%s",
  },
  description: "Generated by create next app",
};

const page = () => {
  return (
    <Suppliers />
  )
}

export default page