import Reports from "@/components/Reports"
export const metadata = {
  title: {
    // absolute: "",
    default: "Reports",
    template: "%s",
  },
  description: "Generated by create next app",
};
const page = () => {
  return (
   <Reports />
  )
}

export default page