import ProductManagement from "@/components/ProductManagement";
export const metadata = {
  title: {
    // absolute: "",
    default: "Product",
    template: "%s",
  },
  description: "Generated by create next app",
};
const page = () => {
  return <ProductManagement />;
};

export default page;
