import SalesInvoices from "@/components/SalesInvoices"
export const metadata = {
  title: {
    // absolute: "",
    default: "SalesInvoices",
    template: "%s",
  },
  description: "Generated by create next app",
};
const page = () => {
  return (
   <>
   <SalesInvoices />
   </>
  )
}

export default page