import PurchaseInvoices from "@/components/PurchaseInvoices";
export const metadata = {
  title: {
    // absolute: "",
    default: "PurchaseInvoices",
    template: "%s",
  },
  description: "Generated by create next app",
};

const page = () => {
  return <PurchaseInvoices />;
};

export default page;
